// Intelligent emoji mapping for viral social infographics
const EMOJI_MAP: Record<string, string> = {
  coffee: '☕',
  caffeine: '☕',
  tea: '🍵',
  beer: '🍺',
  wine: '🍷',
  drink: '🥤',
  water: '💧',
  code: '💻',
  coding: '💻',
  developer: '🧑‍💻',
  programming: '💻',
  software: '💻',
  bug: '🐛',
  debugging: '🔍',
  git: '🌿',
  meeting: '📅',
  zoom: '📹',
  slack: '💬',
  email: '✉️',
  sleep: '😴',
  bed: '🛌',
  awake: '👁️',
  thinking: '🤔',
  planning: '📝',
  reading: '📚',
  docs: '📑',
  salary: '💰',
  money: '💵',
  revenue: '📈',
  profit: '💹',
  spending: '💳',
  expense: '💸',
  budget: '📊',
  rent: '🏠',
  housing: '🏡',
  mortgage: '🏦',
  food: '🍔',
  dining: '🍽️',
  groceries: '🛒',
  delivery: '🛵',
  pizza: '🍕',
  shopping: '🛍️',
  amazon: '📦',
  subscription: '🔄',
  savings: '🪙',
  investment: '📈',
  crypto: '💎',
  bitcoin: '🪙',
  btc: '🪙',
  ethereum: '🔷',
  eth: '🔷',
  solana: '🟣',
  travel: '✈️',
  flight: '🛫',
  vacation: '🏝️',
  transport: '🚗',
  car: '🚙',
  gas: '⛽',
  uber: '🚕',
  fitness: '💪',
  gym: '🏋️',
  workout: '🏃',
  running: '🏃‍♂️',
  gaming: '🎮',
  game: '🕹️',
  netflix: '🍿',
  movie: '🎬',
  music: '🎵',
  spotify: '🎧',
  youtube: '▶️',
  tiktok: '📱',
  instagram: '📸',
  twitter: '🐦',
  reddit: '🤖',
  android: '🤖',
  apple: '🍎',
  ios: '🍏',
  chrome: '🌐',
  safari: '🧭',
  firefox: '🦊',
  edge: '🌊',
  python: '🐍',
  javascript: '⚡',
  typescript: '🔷',
  rust: '🦀',
  golang: '🐹',
  ai: '✨',
  agent: '🤖',
  model: '🧠',
  agree: '👍',
  disagree: '👎',
  yes: '✅',
  no: '❌',
  success: '🎯',
  error: '⚠️'
};

export function decorateItemWithEmoji(name: string): string {
  // If string already starts with an emoji, return as-is
  const hasEmoji = /\p{Extended_Pictographic}/u.test(name.slice(0, 4));
  if (hasEmoji) return name;

  const lower = name.toLowerCase();
  for (const [key, emoji] of Object.entries(EMOJI_MAP)) {
    if (lower.includes(key)) {
      return `${emoji} ${name}`;
    }
  }

  // Fallback category emojis if nothing matched
  return `✨ ${name}`;
}
