// Sample datasets carried over from the v2 template gallery. Illustrative only;
// every card that uses one says so. Generated from the archived chartPresets.ts.
import type { ChartType, Row } from './types';

export interface LegacyPreset { key: string; category: 'viral' | 'tech' | 'finance' | 'business'; title: string; subtitle: string; type: ChartType; rows: Row[] }

export const LEGACY_PRESETS: LegacyPreset[] = [
  { key: 'memeCoding', category: 'viral', title: 'Where My 8-Hour Workday Actually Goes', subtitle: 'Source: Developer Reality Audit', type: 'pie', rows: [{ id: 'memeCoding-1', label: 'Thinking about how to code', value: 38 }, { id: 'memeCoding-2', label: 'Reading docs & StackOverflow', value: 24 }, { id: 'memeCoding-3', label: 'Meetings that could be a DM', value: 18 }, { id: 'memeCoding-4', label: 'Writing actual code', value: 12 }, { id: 'memeCoding-5', label: 'Fighting git merge conflicts', value: 8 }] },
  { key: 'memeSalary', category: 'viral', title: 'Where My Monthly Salary Actually Vanishes', subtitle: 'Bank Account Forensic Breakdown', type: 'donut', rows: [{ id: 'memeSalary-1', label: 'Rent & Utilities', value: 45 }, { id: 'memeSalary-2', label: 'Coffee & Food Delivery', value: 25 }, { id: 'memeSalary-3', label: 'Forgot-to-cancel Subscriptions', value: 15 }, { id: 'memeSalary-4', label: 'Impulse Online Shopping', value: 10 }, { id: 'memeSalary-5', label: 'Actual Savings', value: 5 }] },
  { key: 'memeMeeting', category: 'viral', title: 'Anatomy of a 1-Hour Zoom Meeting', subtitle: 'Efficiency Breakdown', type: 'bar', rows: [{ id: 'memeMeeting-1', label: '"Can you see my screen?"', value: 18 }, { id: 'memeMeeting-2', label: '"You were on mute"', value: 14 }, { id: 'memeMeeting-3', label: 'Awkward silence after question', value: 22 }, { id: 'memeMeeting-4', label: 'Small talk about weather', value: 12 }, { id: 'memeMeeting-5', label: 'Actual productive decision', value: 6 }] },
  { key: 'aiMarket', category: 'tech', title: '2026 AI Developer Workflow Share', subtitle: 'State of Autonomous Software Engineering', type: 'bar', rows: [{ id: 'aiMarket-1', label: 'Coding Agents', value: 44 }, { id: 'aiMarket-2', label: 'Copilot Auto-complete', value: 26 }, { id: 'aiMarket-3', label: 'Chat Reasoning Models', value: 18 }, { id: 'aiMarket-4', label: 'Manual Syntax Writing', value: 12 }] },
  { key: 'marketShare', category: 'tech', title: 'Global Smartphone OS Market Share', subtitle: 'Source: Mobile Analytics 2026', type: 'pie', rows: [{ id: 'marketShare-1', label: 'Android', value: 71.4 }, { id: 'marketShare-2', label: 'iOS', value: 27.8 }, { id: 'marketShare-3', label: 'KaiOS', value: 0.5 }, { id: 'marketShare-4', label: 'Others', value: 0.3 }] },
  { key: 'revenueGrowth', category: 'finance', title: 'Quarterly SaaS Revenue ($k)', subtitle: 'Fiscal Year Performance Curve', type: 'line', rows: [{ id: 'revenueGrowth-1', label: 'Q1 2026', value: 145 }, { id: 'revenueGrowth-2', label: 'Q2 2026', value: 230 }, { id: 'revenueGrowth-3', label: 'Q3 2026', value: 310 }, { id: 'revenueGrowth-4', label: 'Q4 2026', value: 480 }] },
  { key: 'trafficSources', category: 'business', title: 'Website Visitor Traffic Breakdown', subtitle: 'Monthly Organic vs Direct vs Social', type: 'horizontalBar', rows: [{ id: 'trafficSources-1', label: 'Organic Search', value: 52000 }, { id: 'trafficSources-2', label: 'Direct Traffic', value: 24000 }, { id: 'trafficSources-3', label: 'Social Media', value: 18000 }, { id: 'trafficSources-4', label: 'Referrals', value: 9500 }, { id: 'trafficSources-5', label: 'Email Campaigns', value: 6200 }] },
  { key: 'budgetAllocation', category: 'business', title: 'Startup Annual Budget Allocation', subtitle: 'Engineering & Marketing Priority', type: 'donut', rows: [{ id: 'budgetAllocation-1', label: 'Engineering & Product', value: 45 }, { id: 'budgetAllocation-2', label: 'Growth Marketing', value: 25 }, { id: 'budgetAllocation-3', label: 'Sales & BD', value: 15 }, { id: 'budgetAllocation-4', label: 'Operations & Legal', value: 10 }, { id: 'budgetAllocation-5', label: 'Customer Success', value: 5 }] },
  { key: 'cryptoPortfolio', category: 'finance', title: 'DeFi & Crypto Asset Allocation', subtitle: 'Portfolio Holding Distribution', type: 'pie', rows: [{ id: 'cryptoPortfolio-1', label: 'Bitcoin (BTC)', value: 40 }, { id: 'cryptoPortfolio-2', label: 'Ethereum (ETH)', value: 30 }, { id: 'cryptoPortfolio-3', label: 'Solana (SOL)', value: 15 }, { id: 'cryptoPortfolio-4', label: 'Stablecoins (USDC)', value: 10 }, { id: 'cryptoPortfolio-5', label: 'Altcoins', value: 5 }] },
  { key: 'skillRadar', category: 'tech', title: 'Full-Stack Developer Skill Matrix', subtitle: 'Proficiency Score Out of 100', type: 'radar', rows: [{ id: 'skillRadar-1', label: 'React & Next.js', value: 95 }, { id: 'skillRadar-2', label: 'TypeScript', value: 90 }, { id: 'skillRadar-3', label: 'UI & Design Tokens', value: 92 }, { id: 'skillRadar-4', label: 'Backend & APIs', value: 85 }, { id: 'skillRadar-5', label: 'Database & SQL', value: 80 }, { id: 'skillRadar-6', label: 'Performance & SEO', value: 94 }] },
];
