/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as BarGraphMakerRouteImport } from './routes/bar-graph-maker'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as ChartsRouteImport } from './routes/charts'
import { Route as ConvertExcelToChartRouteImport } from './routes/convert-excel-to-chart'
import { Route as NewRouteImport } from './routes/new'
import { Route as PieChartMakerRouteImport } from './routes/pie-chart-maker'
import { Route as SeriesRouteImport } from './routes/series'
import { Route as EditIdRouteImport } from './routes/edit.$id'
import { Route as SIndexRouteImport } from './routes/s.index'
import { Route as SStateRouteImport } from './routes/s.$state'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BarGraphMakerRoute = BarGraphMakerRouteImport.update({
  id: '/bar-graph-maker',
  path: '/bar-graph-maker',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartsRoute = ChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvertExcelToChartRoute = ConvertExcelToChartRouteImport.update({
  id: '/convert-excel-to-chart',
  path: '/convert-excel-to-chart',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PieChartMakerRoute = PieChartMakerRouteImport.update({
  id: '/pie-chart-maker',
  path: '/pie-chart-maker',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesRoute = SeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => rootRouteImport,
} as any)
const EditIdRoute = EditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SIndexRoute = SIndexRouteImport.update({
  id: '/s/',
  path: '/s/',
  getParentRoute: () => rootRouteImport,
} as any)
const SStateRoute = SStateRouteImport.update({
  id: '/s/$state',
  path: '/s/$state',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/bar-graph-maker': typeof BarGraphMakerRoute
  '/brand': typeof BrandRoute
  '/charts': typeof ChartsRoute
  '/convert-excel-to-chart': typeof ConvertExcelToChartRoute
  '/new': typeof NewRoute
  '/pie-chart-maker': typeof PieChartMakerRoute
  '/series': typeof SeriesRoute
  '/edit/$id': typeof EditIdRoute
  '/s/$state': typeof SStateRoute
  '/s/': typeof SIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/bar-graph-maker': typeof BarGraphMakerRoute
  '/brand': typeof BrandRoute
  '/charts': typeof ChartsRoute
  '/convert-excel-to-chart': typeof ConvertExcelToChartRoute
  '/new': typeof NewRoute
  '/pie-chart-maker': typeof PieChartMakerRoute
  '/series': typeof SeriesRoute
  '/edit/$id': typeof EditIdRoute
  '/s/$state': typeof SStateRoute
  '/s': typeof SIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/bar-graph-maker': typeof BarGraphMakerRoute
  '/brand': typeof BrandRoute
  '/charts': typeof ChartsRoute
  '/convert-excel-to-chart': typeof ConvertExcelToChartRoute
  '/new': typeof NewRoute
  '/pie-chart-maker': typeof PieChartMakerRoute
  '/series': typeof SeriesRoute
  '/edit/$id': typeof EditIdRoute
  '/s/$state': typeof SStateRoute
  '/s/': typeof SIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/bar-graph-maker'
    | '/brand'
    | '/charts'
    | '/convert-excel-to-chart'
    | '/new'
    | '/pie-chart-maker'
    | '/series'
    | '/edit/$id'
    | '/s/$state'
    | '/s/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/bar-graph-maker'
    | '/brand'
    | '/charts'
    | '/convert-excel-to-chart'
    | '/new'
    | '/pie-chart-maker'
    | '/series'
    | '/edit/$id'
    | '/s/$state'
    | '/s'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/bar-graph-maker'
    | '/brand'
    | '/charts'
    | '/convert-excel-to-chart'
    | '/new'
    | '/pie-chart-maker'
    | '/series'
    | '/edit/$id'
    | '/s/$state'
    | '/s/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  BarGraphMakerRoute: typeof BarGraphMakerRoute
  BrandRoute: typeof BrandRoute
  ChartsRoute: typeof ChartsRoute
  ConvertExcelToChartRoute: typeof ConvertExcelToChartRoute
  NewRoute: typeof NewRoute
  PieChartMakerRoute: typeof PieChartMakerRoute
  SeriesRoute: typeof SeriesRoute
  EditIdRoute: typeof EditIdRoute
  SStateRoute: typeof SStateRoute
  SIndexRoute: typeof SIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bar-graph-maker': {
      id: '/bar-graph-maker'
      path: '/bar-graph-maker'
      fullPath: '/bar-graph-maker'
      preLoaderRoute: typeof BarGraphMakerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts': {
      id: '/charts'
      path: '/charts'
      fullPath: '/charts'
      preLoaderRoute: typeof ChartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convert-excel-to-chart': {
      id: '/convert-excel-to-chart'
      path: '/convert-excel-to-chart'
      fullPath: '/convert-excel-to-chart'
      preLoaderRoute: typeof ConvertExcelToChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pie-chart-maker': {
      id: '/pie-chart-maker'
      path: '/pie-chart-maker'
      fullPath: '/pie-chart-maker'
      preLoaderRoute: typeof PieChartMakerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series': {
      id: '/series'
      path: '/series'
      fullPath: '/series'
      preLoaderRoute: typeof SeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit/$id': {
      id: '/edit/$id'
      path: '/edit/$id'
      fullPath: '/edit/$id'
      preLoaderRoute: typeof EditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/': {
      id: '/s/'
      path: '/s'
      fullPath: '/s/'
      preLoaderRoute: typeof SIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$state': {
      id: '/s/$state'
      path: '/s/$state'
      fullPath: '/s/$state'
      preLoaderRoute: typeof SStateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  BarGraphMakerRoute: BarGraphMakerRoute,
  BrandRoute: BrandRoute,
  ChartsRoute: ChartsRoute,
  ConvertExcelToChartRoute: ConvertExcelToChartRoute,
  NewRoute: NewRoute,
  PieChartMakerRoute: PieChartMakerRoute,
  SeriesRoute: SeriesRoute,
  EditIdRoute: EditIdRoute,
  SStateRoute: SStateRoute,
  SIndexRoute: SIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
